Document: windows-binaries
Title: Debian windows-binaries Manual
Author: <insert document author here>
Abstract: This manual describes what windows-binaries is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/windows-binaries/windows-binaries.sgml.gz

Format: postscript
Files: /usr/share/doc/windows-binaries/windows-binaries.ps.gz

Format: text
Files: /usr/share/doc/windows-binaries/windows-binaries.text.gz

Format: HTML
Index: /usr/share/doc/windows-binaries/html/index.html
Files: /usr/share/doc/windows-binaries/html/*.html
